package css 

    // autogenerated from properties.go
    
func (s Properties) GetStringSet() StringSet {
    return s["string_set"].(StringSet)
}
func (s Properties) SetStringSet(v StringSet) {
    s["string_set"] = v
}

func (s Properties) GetBackgroundImage() Images {
    return s["background_image"].(Images)
}
func (s Properties) SetBackgroundImage(v Images) {
    s["background_image"] = v
}

func (s Properties) GetBackgroundPosition() Centers {
    return s["background_position"].(Centers)
}
func (s Properties) SetBackgroundPosition(v Centers) {
    s["background_position"] = v
}

func (s Properties) GetBackgroundSize() Sizes {
    return s["background_size"].(Sizes)
}
func (s Properties) SetBackgroundSize(v Sizes) {
    s["background_size"] = v
}

func (s Properties) GetBackgroundRepeat() Repeats {
    return s["background_repeat"].(Repeats)
}
func (s Properties) SetBackgroundRepeat(v Repeats) {
    s["background_repeat"] = v
}

func (s Properties) GetBackgroundClip() Strings {
    return s["background_clip"].(Strings)
}
func (s Properties) SetBackgroundClip(v Strings) {
    s["background_clip"] = v
}

func (s Properties) GetBackgroundOrigin() Strings {
    return s["background_origin"].(Strings)
}
func (s Properties) SetBackgroundOrigin(v Strings) {
    s["background_origin"] = v
}

func (s Properties) GetBackgroundAttachment() Strings {
    return s["background_attachment"].(Strings)
}
func (s Properties) SetBackgroundAttachment(v Strings) {
    s["background_attachment"] = v
}

func (s Properties) GetFontFamilly() Strings {
    return s["font_familly"].(Strings)
}
func (s Properties) SetFontFamilly(v Strings) {
    s["font_familly"] = v
}

func (s Properties) GetContent() SContent {
    return s["content"].(SContent)
}
func (s Properties) SetContent(v SContent) {
    s["content"] = v
}

func (s Properties) GetTransform() Transforms {
    return s["transform"].(Transforms)
}
func (s Properties) SetTransform(v Transforms) {
    s["transform"] = v
}

func (s Properties) GetTransformOrigin() Values {
    return s["transform_origin"].(Values)
}
func (s Properties) SetTransformOrigin(v Values) {
    s["transform_origin"] = v
}

func (s Properties) GetBorderSpacing() Values {
    return s["border_spacing"].(Values)
}
func (s Properties) SetBorderSpacing(v Values) {
    s["border_spacing"] = v
}

func (s Properties) GetSize() Values {
    return s["size"].(Values)
}
func (s Properties) SetSize(v Values) {
    s["size"] = v
}

func (s Properties) GetClip() Values {
    return s["clip"].(Values)
}
func (s Properties) SetClip(v Values) {
    s["clip"] = v
}

func (s Properties) GetBorderTopLeftRadius() Values {
    return s["border_top_left_radius"].(Values)
}
func (s Properties) SetBorderTopLeftRadius(v Values) {
    s["border_top_left_radius"] = v
}

func (s Properties) GetBorderTopRightRadius() Values {
    return s["border_top_right_radius"].(Values)
}
func (s Properties) SetBorderTopRightRadius(v Values) {
    s["border_top_right_radius"] = v
}

func (s Properties) GetBorderBottomLeftRadius() Values {
    return s["border_bottom_left_radius"].(Values)
}
func (s Properties) SetBorderBottomLeftRadius(v Values) {
    s["border_bottom_left_radius"] = v
}

func (s Properties) GetBorderBottomRightRadius() Values {
    return s["border_bottom_right_radius"].(Values)
}
func (s Properties) SetBorderBottomRightRadius(v Values) {
    s["border_bottom_right_radius"] = v
}

func (s Properties) GetFontFeatureSettings() SIntStrings {
    return s["font_feature_settings"].(SIntStrings)
}
func (s Properties) SetFontFeatureSettings(v SIntStrings) {
    s["font_feature_settings"] = v
}

func (s Properties) GetPage() Page {
    return s["page"].(Page)
}
func (s Properties) SetPage(v Page) {
    s["page"] = v
}

func (s Properties) GetColor() Color {
    return s["color"].(Color)
}
func (s Properties) SetColor(v Color) {
    s["color"] = v
}

func (s Properties) GetBackgroundColor() Color {
    return s["background_color"].(Color)
}
func (s Properties) SetBackgroundColor(v Color) {
    s["background_color"] = v
}

func (s Properties) GetLink() NamedString {
    return s["link"].(NamedString)
}
func (s Properties) SetLink(v NamedString) {
    s["link"] = v
}

func (s Properties) GetAnchor() NamedString {
    return s["anchor"].(NamedString)
}
func (s Properties) SetAnchor(v NamedString) {
    s["anchor"] = v
}

func (s Properties) GetLang() NamedString {
    return s["lang"].(NamedString)
}
func (s Properties) SetLang(v NamedString) {
    s["lang"] = v
}

func (s Properties) GetMarks() Marks {
    return s["marks"].(Marks)
}
func (s Properties) SetMarks(v Marks) {
    s["marks"] = v
}

func (s Properties) GetFontWeight() IntString {
    return s["font_weight"].(IntString)
}
func (s Properties) SetFontWeight(v IntString) {
    s["font_weight"] = v
}

func (s Properties) GetBreakAfter() String {
    return s["break_after"].(String)
}
func (s Properties) SetBreakAfter(v String) {
    s["break_after"] = v
}

func (s Properties) GetBreakBefore() String {
    return s["break_before"].(String)
}
func (s Properties) SetBreakBefore(v String) {
    s["break_before"] = v
}

func (s Properties) GetDisplay() String {
    return s["display"].(String)
}
func (s Properties) SetDisplay(v String) {
    s["display"] = v
}

func (s Properties) GetFloat() String {
    return s["float"].(String)
}
func (s Properties) SetFloat(v String) {
    s["float"] = v
}

func (s Properties) GetTop() Value {
    return s["top"].(Value)
}
func (s Properties) SetTop(v Value) {
    s["top"] = v
}

func (s Properties) GetRight() Value {
    return s["right"].(Value)
}
func (s Properties) SetRight(v Value) {
    s["right"] = v
}

func (s Properties) GetLeft() Value {
    return s["left"].(Value)
}
func (s Properties) SetLeft(v Value) {
    s["left"] = v
}

func (s Properties) GetBottom() Value {
    return s["bottom"].(Value)
}
func (s Properties) SetBottom(v Value) {
    s["bottom"] = v
}

func (s Properties) GetMarginTop() Value {
    return s["margin_top"].(Value)
}
func (s Properties) SetMarginTop(v Value) {
    s["margin_top"] = v
}

func (s Properties) GetMarginRight() Value {
    return s["margin_right"].(Value)
}
func (s Properties) SetMarginRight(v Value) {
    s["margin_right"] = v
}

func (s Properties) GetMarginBottom() Value {
    return s["margin_bottom"].(Value)
}
func (s Properties) SetMarginBottom(v Value) {
    s["margin_bottom"] = v
}

func (s Properties) GetMarginLeft() Value {
    return s["margin_left"].(Value)
}
func (s Properties) SetMarginLeft(v Value) {
    s["margin_left"] = v
}

func (s Properties) GetHeight() Value {
    return s["height"].(Value)
}
func (s Properties) SetHeight(v Value) {
    s["height"] = v
}

func (s Properties) GetWidth() Value {
    return s["width"].(Value)
}
func (s Properties) SetWidth(v Value) {
    s["width"] = v
}

func (s Properties) GetMinWidth() Value {
    return s["min_width"].(Value)
}
func (s Properties) SetMinWidth(v Value) {
    s["min_width"] = v
}

func (s Properties) GetMinHeight() Value {
    return s["min_height"].(Value)
}
func (s Properties) SetMinHeight(v Value) {
    s["min_height"] = v
}

func (s Properties) GetMaxWidth() Value {
    return s["max_width"].(Value)
}
func (s Properties) SetMaxWidth(v Value) {
    s["max_width"] = v
}

func (s Properties) GetMaxHeight() Value {
    return s["max_height"].(Value)
}
func (s Properties) SetMaxHeight(v Value) {
    s["max_height"] = v
}

func (s Properties) GetPaddingTop() Value {
    return s["padding_top"].(Value)
}
func (s Properties) SetPaddingTop(v Value) {
    s["padding_top"] = v
}

func (s Properties) GetPaddingRight() Value {
    return s["padding_right"].(Value)
}
func (s Properties) SetPaddingRight(v Value) {
    s["padding_right"] = v
}

func (s Properties) GetPaddingBottom() Value {
    return s["padding_bottom"].(Value)
}
func (s Properties) SetPaddingBottom(v Value) {
    s["padding_bottom"] = v
}

func (s Properties) GetPaddingLeft() Value {
    return s["padding_left"].(Value)
}
func (s Properties) SetPaddingLeft(v Value) {
    s["padding_left"] = v
}

func (s Properties) GetTextIndent() Value {
    return s["text_indent"].(Value)
}
func (s Properties) SetTextIndent(v Value) {
    s["text_indent"] = v
}

func (s Properties) GetHyphenateLimitZone() Value {
    return s["hyphenate_limit_zone"].(Value)
}
func (s Properties) SetHyphenateLimitZone(v Value) {
    s["hyphenate_limit_zone"] = v
}

func (s Properties) GetBleedLeft() Value {
    return s["bleed_left"].(Value)
}
func (s Properties) SetBleedLeft(v Value) {
    s["bleed_left"] = v
}

func (s Properties) GetBleedRight() Value {
    return s["bleed_right"].(Value)
}
func (s Properties) SetBleedRight(v Value) {
    s["bleed_right"] = v
}

func (s Properties) GetBleedTop() Value {
    return s["bleed_top"].(Value)
}
func (s Properties) SetBleedTop(v Value) {
    s["bleed_top"] = v
}

func (s Properties) GetBleedBottom() Value {
    return s["bleed_bottom"].(Value)
}
func (s Properties) SetBleedBottom(v Value) {
    s["bleed_bottom"] = v
}

func (s Properties) GetBorderTopWidth() Value {
    return s["border_top_width"].(Value)
}
func (s Properties) SetBorderTopWidth(v Value) {
    s["border_top_width"] = v
}

func (s Properties) GetBorderRightWidth() Value {
    return s["border_right_width"].(Value)
}
func (s Properties) SetBorderRightWidth(v Value) {
    s["border_right_width"] = v
}

func (s Properties) GetBorderLeftWidth() Value {
    return s["border_left_width"].(Value)
}
func (s Properties) SetBorderLeftWidth(v Value) {
    s["border_left_width"] = v
}

func (s Properties) GetBorderBottomWidth() Value {
    return s["border_bottom_width"].(Value)
}
func (s Properties) SetBorderBottomWidth(v Value) {
    s["border_bottom_width"] = v
}

func (s Properties) GetColumnRuleWidth() Value {
    return s["column_rule_width"].(Value)
}
func (s Properties) SetColumnRuleWidth(v Value) {
    s["column_rule_width"] = v
}

func (s Properties) GetOutlineWidth() Value {
    return s["outline_width"].(Value)
}
func (s Properties) SetOutlineWidth(v Value) {
    s["outline_width"] = v
}

func (s Properties) GetLetterSpacing() Value {
    return s["letter_spacing"].(Value)
}
func (s Properties) SetLetterSpacing(v Value) {
    s["letter_spacing"] = v
}

func (s Properties) GetColumnWidth() Value {
    return s["column_width"].(Value)
}
func (s Properties) SetColumnWidth(v Value) {
    s["column_width"] = v
}

func (s Properties) GetColumnGap() Value {
    return s["column_gap"].(Value)
}
func (s Properties) SetColumnGap(v Value) {
    s["column_gap"] = v
}

func (s Properties) GetFontSize() Value {
    return s["font_size"].(Value)
}
func (s Properties) SetFontSize(v Value) {
    s["font_size"] = v
}

func (s Properties) GetLineHeight() Value {
    return s["line_height"].(Value)
}
func (s Properties) SetLineHeight(v Value) {
    s["line_height"] = v
}

func (s Properties) GetTabSize() Value {
    return s["tab_size"].(Value)
}
func (s Properties) SetTabSize(v Value) {
    s["tab_size"] = v
}

func (s Properties) GetVerticalAlign() Value {
    return s["vertical_align"].(Value)
}
func (s Properties) SetVerticalAlign(v Value) {
    s["vertical_align"] = v
}

func (s Properties) GetWordSpacing() Value {
    return s["word_spacing"].(Value)
}
func (s Properties) SetWordSpacing(v Value) {
    s["word_spacing"] = v
}
