package css

// autogenerated from properties.go

func (s Properties) GetStringSet() StringSet {
	return s["string-set"].(StringSet)
}
func (s Properties) SetStringSet(v StringSet) {
	s["string-set"] = v
}

func (s Properties) GetBackgroundImage() Images {
	return s["background-image"].(Images)
}
func (s Properties) SetBackgroundImage(v Images) {
	s["background-image"] = v
}

func (s Properties) GetBackgroundPosition() Centers {
	return s["background-position"].(Centers)
}
func (s Properties) SetBackgroundPosition(v Centers) {
	s["background-position"] = v
}

func (s Properties) GetBackgroundSize() Sizes {
	return s["background-size"].(Sizes)
}
func (s Properties) SetBackgroundSize(v Sizes) {
	s["background-size"] = v
}

func (s Properties) GetBackgroundRepeat() Repeats {
	return s["background-repeat"].(Repeats)
}
func (s Properties) SetBackgroundRepeat(v Repeats) {
	s["background-repeat"] = v
}

func (s Properties) GetBackgroundClip() Strings {
	return s["background-clip"].(Strings)
}
func (s Properties) SetBackgroundClip(v Strings) {
	s["background-clip"] = v
}

func (s Properties) GetBackgroundOrigin() Strings {
	return s["background-origin"].(Strings)
}
func (s Properties) SetBackgroundOrigin(v Strings) {
	s["background-origin"] = v
}

func (s Properties) GetFontFamilly() Strings {
	return s["font-familly"].(Strings)
}
func (s Properties) SetFontFamilly(v Strings) {
	s["font-familly"] = v
}

func (s Properties) GetContent() SContent {
	return s["content"].(SContent)
}
func (s Properties) SetContent(v SContent) {
	s["content"] = v
}

func (s Properties) GetTransform() Transforms {
	return s["transform"].(Transforms)
}
func (s Properties) SetTransform(v Transforms) {
	s["transform"] = v
}

func (s Properties) GetTransformOrigin() Values {
	return s["transform-origin"].(Values)
}
func (s Properties) SetTransformOrigin(v Values) {
	s["transform-origin"] = v
}

func (s Properties) GetBorderSpacing() Values {
	return s["border-spacing"].(Values)
}
func (s Properties) SetBorderSpacing(v Values) {
	s["border-spacing"] = v
}

func (s Properties) GetSize() Values {
	return s["size"].(Values)
}
func (s Properties) SetSize(v Values) {
	s["size"] = v
}

func (s Properties) GetClip() Values {
	return s["clip"].(Values)
}
func (s Properties) SetClip(v Values) {
	s["clip"] = v
}

func (s Properties) GetBorderTopLeftRadius() Values {
	return s["border-top-left-radius"].(Values)
}
func (s Properties) SetBorderTopLeftRadius(v Values) {
	s["border-top-left-radius"] = v
}

func (s Properties) GetBorderTopRightRadius() Values {
	return s["border-top-right-radius"].(Values)
}
func (s Properties) SetBorderTopRightRadius(v Values) {
	s["border-top-right-radius"] = v
}

func (s Properties) GetBorderBottomLeftRadius() Values {
	return s["border-bottom-left-radius"].(Values)
}
func (s Properties) SetBorderBottomLeftRadius(v Values) {
	s["border-bottom-left-radius"] = v
}

func (s Properties) GetBorderBottomRightRadius() Values {
	return s["border-bottom-right-radius"].(Values)
}
func (s Properties) SetBorderBottomRightRadius(v Values) {
	s["border-bottom-right-radius"] = v
}

func (s Properties) GetFontFeatureSettings() SIntStrings {
	return s["font-feature-settings"].(SIntStrings)
}
func (s Properties) SetFontFeatureSettings(v SIntStrings) {
	s["font-feature-settings"] = v
}

func (s Properties) GetPage() Page {
	return s["page"].(Page)
}
func (s Properties) SetPage(v Page) {
	s["page"] = v
}

func (s Properties) GetColor() Color {
	return s["color"].(Color)
}
func (s Properties) SetColor(v Color) {
	s["color"] = v
}

func (s Properties) GetLink() NamedString {
	return s["link"].(NamedString)
}
func (s Properties) SetLink(v NamedString) {
	s["link"] = v
}

func (s Properties) GetAnchor() NamedString {
	return s["anchor"].(NamedString)
}
func (s Properties) SetAnchor(v NamedString) {
	s["anchor"] = v
}

func (s Properties) GetLang() NamedString {
	return s["lang"].(NamedString)
}
func (s Properties) SetLang(v NamedString) {
	s["lang"] = v
}

func (s Properties) GetMarks() Marks {
	return s["marks"].(Marks)
}
func (s Properties) SetMarks(v Marks) {
	s["marks"] = v
}

func (s Properties) GetFontWeight() IntString {
	return s["font-weight"].(IntString)
}
func (s Properties) SetFontWeight(v IntString) {
	s["font-weight"] = v
}

func (s Properties) GetBreakAfter() String {
	return s["break-after"].(String)
}
func (s Properties) SetBreakAfter(v String) {
	s["break-after"] = v
}

func (s Properties) GetBreakBefore() String {
	return s["break-before"].(String)
}
func (s Properties) SetBreakBefore(v String) {
	s["break-before"] = v
}

func (s Properties) GetDisplay() String {
	return s["display"].(String)
}
func (s Properties) SetDisplay(v String) {
	s["display"] = v
}

func (s Properties) GetFloat() String {
	return s["float"].(String)
}
func (s Properties) SetFloat(v String) {
	s["float"] = v
}

func (s Properties) GetTop() Value {
	return s["top"].(Value)
}
func (s Properties) SetTop(v Value) {
	s["top"] = v
}

func (s Properties) GetRight() Value {
	return s["right"].(Value)
}
func (s Properties) SetRight(v Value) {
	s["right"] = v
}

func (s Properties) GetLeft() Value {
	return s["left"].(Value)
}
func (s Properties) SetLeft(v Value) {
	s["left"] = v
}

func (s Properties) GetBottom() Value {
	return s["bottom"].(Value)
}
func (s Properties) SetBottom(v Value) {
	s["bottom"] = v
}

func (s Properties) GetMarginTop() Value {
	return s["margin-top"].(Value)
}
func (s Properties) SetMarginTop(v Value) {
	s["margin-top"] = v
}

func (s Properties) GetMarginRight() Value {
	return s["margin-right"].(Value)
}
func (s Properties) SetMarginRight(v Value) {
	s["margin-right"] = v
}

func (s Properties) GetMarginBottom() Value {
	return s["margin-bottom"].(Value)
}
func (s Properties) SetMarginBottom(v Value) {
	s["margin-bottom"] = v
}

func (s Properties) GetMarginLeft() Value {
	return s["margin-left"].(Value)
}
func (s Properties) SetMarginLeft(v Value) {
	s["margin-left"] = v
}

func (s Properties) GetHeight() Value {
	return s["height"].(Value)
}
func (s Properties) SetHeight(v Value) {
	s["height"] = v
}

func (s Properties) GetWidth() Value {
	return s["width"].(Value)
}
func (s Properties) SetWidth(v Value) {
	s["width"] = v
}

func (s Properties) GetMinWidth() Value {
	return s["min-width"].(Value)
}
func (s Properties) SetMinWidth(v Value) {
	s["min-width"] = v
}

func (s Properties) GetMinHeight() Value {
	return s["min-height"].(Value)
}
func (s Properties) SetMinHeight(v Value) {
	s["min-height"] = v
}

func (s Properties) GetMaxWidth() Value {
	return s["max-width"].(Value)
}
func (s Properties) SetMaxWidth(v Value) {
	s["max-width"] = v
}

func (s Properties) GetMaxHeight() Value {
	return s["max-height"].(Value)
}
func (s Properties) SetMaxHeight(v Value) {
	s["max-height"] = v
}

func (s Properties) GetPaddingTop() Value {
	return s["padding-top"].(Value)
}
func (s Properties) SetPaddingTop(v Value) {
	s["padding-top"] = v
}

func (s Properties) GetPaddingRight() Value {
	return s["padding-right"].(Value)
}
func (s Properties) SetPaddingRight(v Value) {
	s["padding-right"] = v
}

func (s Properties) GetPaddingBottom() Value {
	return s["padding-bottom"].(Value)
}
func (s Properties) SetPaddingBottom(v Value) {
	s["padding-bottom"] = v
}

func (s Properties) GetPaddingLeft() Value {
	return s["padding-left"].(Value)
}
func (s Properties) SetPaddingLeft(v Value) {
	s["padding-left"] = v
}

func (s Properties) GetTextIndent() Value {
	return s["text-indent"].(Value)
}
func (s Properties) SetTextIndent(v Value) {
	s["text-indent"] = v
}

func (s Properties) GetHyphenateLimitZone() Value {
	return s["hyphenate-limit-zone"].(Value)
}
func (s Properties) SetHyphenateLimitZone(v Value) {
	s["hyphenate-limit-zone"] = v
}

func (s Properties) GetBleedLeft() Value {
	return s["bleed-left"].(Value)
}
func (s Properties) SetBleedLeft(v Value) {
	s["bleed-left"] = v
}

func (s Properties) GetBleedRight() Value {
	return s["bleed-right"].(Value)
}
func (s Properties) SetBleedRight(v Value) {
	s["bleed-right"] = v
}

func (s Properties) GetBleedTop() Value {
	return s["bleed-top"].(Value)
}
func (s Properties) SetBleedTop(v Value) {
	s["bleed-top"] = v
}

func (s Properties) GetBleedBottom() Value {
	return s["bleed-bottom"].(Value)
}
func (s Properties) SetBleedBottom(v Value) {
	s["bleed-bottom"] = v
}

func (s Properties) GetBorderTopWidth() Value {
	return s["border-top-width"].(Value)
}
func (s Properties) SetBorderTopWidth(v Value) {
	s["border-top-width"] = v
}

func (s Properties) GetBorderRightWidth() Value {
	return s["border-right-width"].(Value)
}
func (s Properties) SetBorderRightWidth(v Value) {
	s["border-right-width"] = v
}

func (s Properties) GetBorderLeftWidth() Value {
	return s["border-left-width"].(Value)
}
func (s Properties) SetBorderLeftWidth(v Value) {
	s["border-left-width"] = v
}

func (s Properties) GetBorderBottomWidth() Value {
	return s["border-bottom-width"].(Value)
}
func (s Properties) SetBorderBottomWidth(v Value) {
	s["border-bottom-width"] = v
}

func (s Properties) GetColumnRuleWidth() Value {
	return s["column-rule-width"].(Value)
}
func (s Properties) SetColumnRuleWidth(v Value) {
	s["column-rule-width"] = v
}

func (s Properties) GetOutlineWidth() Value {
	return s["outline-width"].(Value)
}
func (s Properties) SetOutlineWidth(v Value) {
	s["outline-width"] = v
}

func (s Properties) GetLetterSpacing() Value {
	return s["letter-spacing"].(Value)
}
func (s Properties) SetLetterSpacing(v Value) {
	s["letter-spacing"] = v
}

func (s Properties) GetColumnWidth() Value {
	return s["column-width"].(Value)
}
func (s Properties) SetColumnWidth(v Value) {
	s["column-width"] = v
}

func (s Properties) GetColumnGap() Value {
	return s["column-gap"].(Value)
}
func (s Properties) SetColumnGap(v Value) {
	s["column-gap"] = v
}

func (s Properties) GetFontSize() Value {
	return s["font-size"].(Value)
}
func (s Properties) SetFontSize(v Value) {
	s["font-size"] = v
}

func (s Properties) GetLineHeight() Value {
	return s["line-height"].(Value)
}
func (s Properties) SetLineHeight(v Value) {
	s["line-height"] = v
}

func (s Properties) GetTabSize() Value {
	return s["tab-size"].(Value)
}
func (s Properties) SetTabSize(v Value) {
	s["tab-size"] = v
}

func (s Properties) GetVerticalAlign() Value {
	return s["vertical-align"].(Value)
}
func (s Properties) SetVerticalAlign(v Value) {
	s["vertical-align"] = v
}

func (s Properties) GetWordSpacing() Value {
	return s["word-spacing"].(Value)
}
func (s Properties) SetWordSpacing(v Value) {
	s["word-spacing"] = v
}
