package properties

// autogenerated from initial_values.go

func (v Center) Copy() ValidatedProperty { return v.Copy3() }
func (v Center) Copy2() CascadedProperty { return v.Copy3() }
func (v Center) Copy3() CssProperty      { return v }

func (v Centers) Copy() ValidatedProperty { return v.Copy3() }
func (v Centers) Copy2() CascadedProperty { return v.Copy3() }
func (v Centers) Copy3() CssProperty {
	out := make(Centers, len(v))
	for i, k := range v {
		out[i] = k
	}
	return out
}

func (v Color) Copy() ValidatedProperty { return v.Copy3() }
func (v Color) Copy2() CascadedProperty { return v.Copy3() }
func (v Color) Copy3() CssProperty      { return v }

func (v ContentProperties) Copy() ValidatedProperty { return v.Copy3() }
func (v ContentProperties) Copy2() CascadedProperty { return v.Copy3() }
func (v ContentProperties) Copy3() CssProperty {
	out := make(ContentProperties, len(v))
	for i, k := range v {
		out[i] = k.copy()
	}
	return out
}

func (v Float) Copy() ValidatedProperty { return v.Copy3() }
func (v Float) Copy2() CascadedProperty { return v.Copy3() }
func (v Float) Copy3() CssProperty      { return v }

func (v Images) Copy() ValidatedProperty { return v.Copy3() }
func (v Images) Copy2() CascadedProperty { return v.Copy3() }
func (v Images) Copy3() CssProperty {
	out := make(Images, len(v))
	for i, k := range v {
		out[i] = k.copyAsImage()
	}
	return out
}

func (v Int) Copy() ValidatedProperty { return v.Copy3() }
func (v Int) Copy2() CascadedProperty { return v.Copy3() }
func (v Int) Copy3() CssProperty      { return v }

func (v IntString) Copy() ValidatedProperty { return v.Copy3() }
func (v IntString) Copy2() CascadedProperty { return v.Copy3() }
func (v IntString) Copy3() CssProperty      { return v }

func (v IntStrings) Copy() ValidatedProperty { return v.Copy3() }
func (v IntStrings) Copy2() CascadedProperty { return v.Copy3() }
func (v IntStrings) Copy3() CssProperty {
	out := make(IntStrings, len(v))
	for i, k := range v {
		out[i] = k
	}
	return out
}

func (v Ints3) Copy() ValidatedProperty { return v.Copy3() }
func (v Ints3) Copy2() CascadedProperty { return v.Copy3() }
func (v Ints3) Copy3() CssProperty      { return v }

func (v Marks) Copy() ValidatedProperty { return v.Copy3() }
func (v Marks) Copy2() CascadedProperty { return v.Copy3() }
func (v Marks) Copy3() CssProperty      { return v }

func (v NDecorations) Copy() ValidatedProperty { return v.Copy3() }
func (v NDecorations) Copy2() CascadedProperty { return v.Copy3() }
func (v NDecorations) Copy3() CssProperty      { return v }

func (v NamedString) Copy() ValidatedProperty { return v.Copy3() }
func (v NamedString) Copy2() CascadedProperty { return v.Copy3() }
func (v NamedString) Copy3() CssProperty      { return v }

func (v Page) Copy() ValidatedProperty { return v.Copy3() }
func (v Page) Copy2() CascadedProperty { return v.Copy3() }
func (v Page) Copy3() CssProperty      { return v }

func (v Point) Copy() ValidatedProperty { return v.Copy3() }
func (v Point) Copy2() CascadedProperty { return v.Copy3() }
func (v Point) Copy3() CssProperty      { return v }

func (v Quotes) Copy() ValidatedProperty { return v.Copy3() }
func (v Quotes) Copy2() CascadedProperty { return v.Copy3() }
func (v Quotes) Copy3() CssProperty {
	out := v
	out.Open = v.Open.copy()
	out.Close = v.Close.copy()

	return out
}

func (v Repeats) Copy() ValidatedProperty { return v.Copy3() }
func (v Repeats) Copy2() CascadedProperty { return v.Copy3() }
func (v Repeats) Copy3() CssProperty {
	out := make(Repeats, len(v))
	for i, k := range v {
		out[i] = k
	}
	return out
}

func (v SContent) Copy() ValidatedProperty { return v.Copy3() }
func (v SContent) Copy2() CascadedProperty { return v.Copy3() }
func (v SContent) Copy3() CssProperty {
	out := v
	out.Contents = v.Contents.copy()

	return out
}

func (v SIntStrings) Copy() ValidatedProperty { return v.Copy3() }
func (v SIntStrings) Copy2() CascadedProperty { return v.Copy3() }
func (v SIntStrings) Copy3() CssProperty {
	out := v
	out.Values = v.Values.copy()

	return out
}

func (v SStrings) Copy() ValidatedProperty { return v.Copy3() }
func (v SStrings) Copy2() CascadedProperty { return v.Copy3() }
func (v SStrings) Copy3() CssProperty {
	out := v
	out.Strings = v.Strings.copy()

	return out
}

func (v Sizes) Copy() ValidatedProperty { return v.Copy3() }
func (v Sizes) Copy2() CascadedProperty { return v.Copy3() }
func (v Sizes) Copy3() CssProperty {
	out := make(Sizes, len(v))
	for i, k := range v {
		out[i] = k
	}
	return out
}

func (v String) Copy() ValidatedProperty { return v.Copy3() }
func (v String) Copy2() CascadedProperty { return v.Copy3() }
func (v String) Copy3() CssProperty      { return v }

func (v StringSet) Copy() ValidatedProperty { return v.Copy3() }
func (v StringSet) Copy2() CascadedProperty { return v.Copy3() }
func (v StringSet) Copy3() CssProperty {
	out := v
	out.Contents = v.Contents.copy()

	return out
}

func (v Strings) Copy() ValidatedProperty { return v.Copy3() }
func (v Strings) Copy2() CascadedProperty { return v.Copy3() }
func (v Strings) Copy3() CssProperty {
	out := make(Strings, len(v))
	for i, k := range v {
		out[i] = k
	}
	return out
}

func (v Transforms) Copy() ValidatedProperty { return v.Copy3() }
func (v Transforms) Copy2() CascadedProperty { return v.Copy3() }
func (v Transforms) Copy3() CssProperty {
	out := make(Transforms, len(v))
	for i, k := range v {
		out[i] = k.copy()
	}
	return out
}

func (v Value) Copy() ValidatedProperty { return v.Copy3() }
func (v Value) Copy2() CascadedProperty { return v.Copy3() }
func (v Value) Copy3() CssProperty      { return v }

func (v Values) Copy() ValidatedProperty { return v.Copy3() }
func (v Values) Copy2() CascadedProperty { return v.Copy3() }
func (v Values) Copy3() CssProperty {
	out := make(Values, len(v))
	for i, k := range v {
		out[i] = k
	}
	return out
}
func (v SDimensions) copy() SDimensions {
	out := v
	out.Dimensions = v.Dimensions.copy()

	return out
}
func (v LinearGradient) copy() LinearGradient {
	out := v
	out.ColorStops = v.ColorStops.copy()

	return out
}
func (v CustomProperty) copy() CustomProperty {
	out := make(CustomProperty, len(v))
	for i, k := range v {
		out[i] = k
	}
	return out
}
func (v ContentProperties) copy() ContentProperties {
	out := make(ContentProperties, len(v))
	for i, k := range v {
		out[i] = k.copy()
	}
	return out
}
func (v ContentProperty) copy() ContentProperty {
	out := v
	out.Content = v.Content.copyAsInnerContents()

	return out
}
func (v RadialGradient) copy() RadialGradient {
	out := v
	out.ColorStops = v.ColorStops.copy()

	return out
}
func (v Dimensions) copy() Dimensions {
	out := make(Dimensions, len(v))
	for i, k := range v {
		out[i] = k
	}
	return out
}
func (v Strings) copy() Strings {
	out := make(Strings, len(v))
	for i, k := range v {
		out[i] = k
	}
	return out
}
func (v IntStrings) copy() IntStrings {
	out := make(IntStrings, len(v))
	for i, k := range v {
		out[i] = k
	}
	return out
}
func (v ColorsStops) copy() ColorsStops {
	out := make(ColorsStops, len(v))
	for i, k := range v {
		out[i] = k
	}
	return out
}
func (v SContents) copy() SContents {
	out := make(SContents, len(v))
	for i, k := range v {
		out[i] = k.copy()
	}
	return out
}
func (v SContent) copy() SContent {
	out := v
	out.Contents = v.Contents.copy()

	return out
}
