package structure

import (
	pr "github.com/benoitkugler/go-weasyprint/style/properties"
	"github.com/benoitkugler/go-weasyprint/style/tree"
)

// autogenerated from boxes.go

func NewBoxFields(elementTag string, style pr.Properties, children []Box) *BoxFields {
	out := BoxFields{
		elementTag: elementTag,
		style:      style,
		children:   children,
	}

	return &out
}
func NewParentBox(elementTag string, style pr.Properties, children []Box) *ParentBox {
	out := ParentBox{}
	parent := NewBoxFields(elementTag, style, children)
	out.BoxFields = *parent
	return &out
}
func ParentBoxAnonymousFrom(parent Box, children []Box) *ParentBox {
	style := tree.ComputedFromCascaded(nil, nil, parent.Box().style, nil, "", "", nil)
	return NewParentBox(parent.Box().elementTag, style, children)
}
func (b ParentBox) Copy() Box { return &b }

func NewBlockLevelBox(elementTag string, style pr.Properties, children []Box) *BlockLevelBox {
	out := BlockLevelBox{}

	return &out
}
func BlockLevelBoxAnonymousFrom(parent Box, children []Box) *BlockLevelBox {
	style := tree.ComputedFromCascaded(nil, nil, parent.Box().style, nil, "", "", nil)
	return NewBlockLevelBox(parent.Box().elementTag, style, children)
}
func (b BlockLevelBox) Copy() Box { return &b }

func NewBlockContainerBox(elementTag string, style pr.Properties, children []Box) *BlockContainerBox {
	out := BlockContainerBox{}
	parent := NewParentBox(elementTag, style, children)
	out.ParentBox = *parent
	return &out
}
func BlockContainerBoxAnonymousFrom(parent Box, children []Box) *BlockContainerBox {
	style := tree.ComputedFromCascaded(nil, nil, parent.Box().style, nil, "", "", nil)
	return NewBlockContainerBox(parent.Box().elementTag, style, children)
}
func (b BlockContainerBox) Copy() Box { return &b }

func NewBlockBox(elementTag string, style pr.Properties, children []Box) *BlockBox {
	out := BlockBox{}
	parent := NewBlockContainerBox(elementTag, style, children)
	out.BlockContainerBox = *parent
	return &out
}
func BlockBoxAnonymousFrom(parent Box, children []Box) *BlockBox {
	style := tree.ComputedFromCascaded(nil, nil, parent.Box().style, nil, "", "", nil)
	return NewBlockBox(parent.Box().elementTag, style, children)
}
func (b BlockBox) Copy() Box { return &b }

func NewLineBox(elementTag string, style pr.Properties, children []Box) *LineBox {
	out := LineBox{
		textOverflow: "clip",
	}
	parent := NewParentBox(elementTag, style, children)
	out.ParentBox = *parent
	return &out
}

func (b LineBox) Copy() Box { return &b }

func NewInlineLevelBox(elementTag string, style pr.Properties, children []Box) *InlineLevelBox {
	out := InlineLevelBox{}
	parent := NewBoxFields(elementTag, style, children)
	out.BoxFields = *parent
	return &out
}
func InlineLevelBoxAnonymousFrom(parent Box, children []Box) *InlineLevelBox {
	style := tree.ComputedFromCascaded(nil, nil, parent.Box().style, nil, "", "", nil)
	return NewInlineLevelBox(parent.Box().elementTag, style, children)
}
func (b InlineLevelBox) Copy() Box { return &b }

func InlineBoxAnonymousFrom(parent Box, children []Box) *InlineBox {
	style := tree.ComputedFromCascaded(nil, nil, parent.Box().style, nil, "", "", nil)
	return NewInlineBox(parent.Box().elementTag, style, children)
}
func (b InlineBox) Copy() Box { return &b }

func TextBoxAnonymousFrom(parent Box, text string) *TextBox {
	style := tree.ComputedFromCascaded(nil, nil, parent.Box().style, nil, "", "", nil)
	return NewTextBox(parent.Box().elementTag, style, text)
}
func (b TextBox) Copy() Box { return &b }

func NewAtomicInlineLevelBox(elementTag string, style pr.Properties, children []Box) *AtomicInlineLevelBox {
	out := AtomicInlineLevelBox{}
	parent := NewInlineLevelBox(elementTag, style, children)
	out.InlineLevelBox = *parent
	return &out
}
func AtomicInlineLevelBoxAnonymousFrom(parent Box, children []Box) *AtomicInlineLevelBox {
	style := tree.ComputedFromCascaded(nil, nil, parent.Box().style, nil, "", "", nil)
	return NewAtomicInlineLevelBox(parent.Box().elementTag, style, children)
}
func (b AtomicInlineLevelBox) Copy() Box { return &b }

func NewInlineBlockBox(elementTag string, style pr.Properties, children []Box) *InlineBlockBox {
	out := InlineBlockBox{}
	parent := NewAtomicInlineLevelBox(elementTag, style, children)
	out.AtomicInlineLevelBox = *parent
	//TODO: handle sharing of same base fields
	out.BlockContainerBox.BoxFields = parent.BoxFields
	return &out
}
func InlineBlockBoxAnonymousFrom(parent Box, children []Box) *InlineBlockBox {
	style := tree.ComputedFromCascaded(nil, nil, parent.Box().style, nil, "", "", nil)
	return NewInlineBlockBox(parent.Box().elementTag, style, children)
}
func (b InlineBlockBox) Copy() Box { return &b }

func NewReplacedBox(elementTag string, style pr.Properties, replacement pr.Image) *ReplacedBox {
	out := ReplacedBox{
		replacement: replacement,
	}
	parent := NewBoxFields(elementTag, style, nil)
	out.BoxFields = *parent
	return &out
}
func ReplacedBoxAnonymousFrom(parent Box, nil pr.Image) *ReplacedBox {
	style := tree.ComputedFromCascaded(nil, nil, parent.Box().style, nil, "", "", nil)
	return NewReplacedBox(parent.Box().elementTag, style, nil)
}
func (b ReplacedBox) Copy() Box { return &b }

func NewBlockReplacedBox(elementTag string, style pr.Properties, replacement pr.Image) *BlockReplacedBox {
	out := BlockReplacedBox{}
	parent := NewReplacedBox(elementTag, style, replacement)
	out.ReplacedBox = *parent
	return &out
}
func BlockReplacedBoxAnonymousFrom(parent Box, replacement pr.Image) *BlockReplacedBox {
	style := tree.ComputedFromCascaded(nil, nil, parent.Box().style, nil, "", "", nil)
	return NewBlockReplacedBox(parent.Box().elementTag, style, replacement)
}

func (b BlockReplacedBox) Copy() Box { return &b }

func NewInlineReplacedBox(elementTag string, style pr.Properties, replacement pr.Image) *InlineReplacedBox {
	out := InlineReplacedBox{}
	parent := NewReplacedBox(elementTag, style, replacement)
	out.ReplacedBox = *parent
	return &out
}
func InlineReplacedBoxAnonymousFrom(parent Box, replacement pr.Image) *InlineReplacedBox {
	style := tree.ComputedFromCascaded(nil, nil, parent.Box().style, nil, "", "", nil)
	return NewInlineReplacedBox(parent.Box().elementTag, style, replacement)
}
func (b InlineReplacedBox) Copy() Box { return &b }

func NewTableBox(elementTag string, style pr.Properties, children []Box) *TableBox {
	out := TableBox{
		tabularContainer: true,
	}
	parent := NewParentBox(elementTag, style, children)
	out.ParentBox = *parent
	return &out
}
func TableBoxAnonymousFrom(parent Box, children []Box) *TableBox {
	style := tree.ComputedFromCascaded(nil, nil, parent.Box().style, nil, "", "", nil)
	return NewTableBox(parent.Box().elementTag, style, children)
}
func (b TableBox) Copy() Box { return &b }

func NewInlineTableBox(elementTag string, style pr.Properties, children []Box) *InlineTableBox {
	out := InlineTableBox{}
	parent := NewTableBox(elementTag, style, children)
	out.TableBox = *parent
	return &out
}
func InlineTableBoxAnonymousFrom(parent Box, children []Box) *InlineTableBox {
	style := tree.ComputedFromCascaded(nil, nil, parent.Box().style, nil, "", "", nil)
	return NewInlineTableBox(parent.Box().elementTag, style, children)
}
func (b InlineTableBox) Copy() Box { return &b }

func NewTableRowGroupBox(elementTag string, style pr.Properties, children []Box) *TableRowGroupBox {
	out := TableRowGroupBox{
		properTableChild:       true,
		internalTableOrCaption: true,
		tabularContainer:       true,
	}
	parent := NewParentBox(elementTag, style, children)
	out.ParentBox = *parent
	return &out
}
func TableRowGroupBoxAnonymousFrom(parent Box, children []Box) *TableRowGroupBox {
	style := tree.ComputedFromCascaded(nil, nil, parent.Box().style, nil, "", "", nil)
	return NewTableRowGroupBox(parent.Box().elementTag, style, children)
}
func (b TableRowGroupBox) Copy() Box { return &b }

func NewTableRowBox(elementTag string, style pr.Properties, children []Box) *TableRowBox {
	out := TableRowBox{
		properTableChild:       true,
		internalTableOrCaption: true,
		tabularContainer:       true,
	}
	parent := NewParentBox(elementTag, style, children)
	out.ParentBox = *parent
	return &out
}
func TableRowBoxAnonymousFrom(parent Box, children []Box) *TableRowBox {
	style := tree.ComputedFromCascaded(nil, nil, parent.Box().style, nil, "", "", nil)
	return NewTableRowBox(parent.Box().elementTag, style, children)
}
func (b TableRowBox) Copy() Box { return &b }

func NewTableColumnGroupBox(elementTag string, style pr.Properties, children []Box) *TableColumnGroupBox {
	out := TableColumnGroupBox{
		properTableChild:       true,
		internalTableOrCaption: true,
		span:                   1,
	}
	parent := NewParentBox(elementTag, style, children)
	out.ParentBox = *parent
	return &out
}
func TableColumnGroupBoxAnonymousFrom(parent Box, children []Box) *TableColumnGroupBox {
	style := tree.ComputedFromCascaded(nil, nil, parent.Box().style, nil, "", "", nil)
	return NewTableColumnGroupBox(parent.Box().elementTag, style, children)
}
func (b TableColumnGroupBox) Copy() Box { return &b }

func NewTableColumnBox(elementTag string, style pr.Properties, children []Box) *TableColumnBox {
	out := TableColumnBox{
		properTableChild:       true,
		internalTableOrCaption: true,
		span:                   1,
	}
	parent := NewParentBox(elementTag, style, children)
	out.ParentBox = *parent
	return &out
}
func TableColumnBoxAnonymousFrom(parent Box, children []Box) *TableColumnBox {
	style := tree.ComputedFromCascaded(nil, nil, parent.Box().style, nil, "", "", nil)
	return NewTableColumnBox(parent.Box().elementTag, style, children)
}
func (b TableColumnBox) Copy() Box { return &b }

func NewTableCellBox(elementTag string, style pr.Properties, children []Box) *TableCellBox {
	out := TableCellBox{
		internalTableOrCaption: true,
		colspan:                1,
		rowspan:                1,
	}
	parent := NewBlockContainerBox(elementTag, style, children)
	out.BlockContainerBox = *parent
	return &out
}
func TableCellBoxAnonymousFrom(parent Box, children []Box) *TableCellBox {
	style := tree.ComputedFromCascaded(nil, nil, parent.Box().style, nil, "", "", nil)
	return NewTableCellBox(parent.Box().elementTag, style, children)
}
func (b TableCellBox) Copy() Box { return &b }

func NewTableCaptionBox(elementTag string, style pr.Properties, children []Box) *TableCaptionBox {
	out := TableCaptionBox{
		properTableChild:       true,
		internalTableOrCaption: true,
	}
	parent := NewBlockBox(elementTag, style, children)
	out.BlockBox = *parent
	return &out
}
func TableCaptionBoxAnonymousFrom(parent Box, children []Box) *TableCaptionBox {
	style := tree.ComputedFromCascaded(nil, nil, parent.Box().style, nil, "", "", nil)
	return NewTableCaptionBox(parent.Box().elementTag, style, children)
}
func (b TableCaptionBox) Copy() Box { return &b }

func (b PageBox) Copy() Box { return &b }

func (b MarginBox) Copy() Box { return &b }

func NewFlexContainerBox(elementTag string, style pr.Properties, children []Box) *FlexContainerBox {
	out := FlexContainerBox{}
	parent := NewParentBox(elementTag, style, children)
	out.ParentBox = *parent
	return &out
}
func FlexContainerBoxAnonymousFrom(parent Box, children []Box) *FlexContainerBox {
	style := tree.ComputedFromCascaded(nil, nil, parent.Box().style, nil, "", "", nil)
	return NewFlexContainerBox(parent.Box().elementTag, style, children)
}
func (b FlexContainerBox) Copy() Box { return &b }

func NewFlexBox(elementTag string, style pr.Properties, children []Box) *FlexBox {
	out := FlexBox{}
	parent := NewFlexContainerBox(elementTag, style, children)
	out.FlexContainerBox = *parent
	return &out
}
func FlexBoxAnonymousFrom(parent Box, children []Box) *FlexBox {
	style := tree.ComputedFromCascaded(nil, nil, parent.Box().style, nil, "", "", nil)
	return NewFlexBox(parent.Box().elementTag, style, children)
}
func (b FlexBox) Copy() Box { return &b }

func NewInlineFlexBox(elementTag string, style pr.Properties, children []Box) *InlineFlexBox {
	out := InlineFlexBox{}
	parent := NewFlexContainerBox(elementTag, style, children)
	out.FlexContainerBox = *parent
	return &out
}
func InlineFlexBoxAnonymousFrom(parent Box, children []Box) *InlineFlexBox {
	style := tree.ComputedFromCascaded(nil, nil, parent.Box().style, nil, "", "", nil)
	return NewInlineFlexBox(parent.Box().elementTag, style, children)
}
func (b InlineFlexBox) Copy() Box { return &b }

var (
	TypeTextBox             BoxType = typeTextBox{}
	TypeTableBox            BoxType = typeTableBox{}
	TypeInlineTableBox      BoxType = typeInlineTableBox{}
	TypeTableRowGroupBox    BoxType = typeTableRowGroupBox{}
	TypeTableRowBox         BoxType = typeTableRowBox{}
	TypeTableColumnGroupBox BoxType = typeTableColumnGroupBox{}
	TypeTableColumnBox      BoxType = typeTableColumnBox{}
	TypeTableCellBox        BoxType = typeTableCellBox{}
)

func (t typeTextBox) IsInstance(box Box) bool {
	_, is := box.(*TextBox)
	return is
}

type typeTextBox struct{}

func (t typeTableBox) AnonymousFrom(parent Box, children []Box) Box {
	return TableBoxAnonymousFrom(parent, children)
}

type typeTableBox struct{}

func (t typeInlineTableBox) AnonymousFrom(parent Box, children []Box) Box {
	return InlineTableBoxAnonymousFrom(parent, children)
}

func (t typeInlineTableBox) IsInstance(box Box) bool {
	_, is := box.(*InlineTableBox)
	return is
}

type typeInlineTableBox struct{}

func (t typeTableRowGroupBox) AnonymousFrom(parent Box, children []Box) Box {
	return TableRowGroupBoxAnonymousFrom(parent, children)
}

func (t typeTableRowGroupBox) IsInstance(box Box) bool {
	_, is := box.(*TableRowGroupBox)
	return is
}

type typeTableRowGroupBox struct{}

func (t typeTableRowBox) AnonymousFrom(parent Box, children []Box) Box {
	return TableRowBoxAnonymousFrom(parent, children)
}

func (t typeTableRowBox) IsInstance(box Box) bool {
	_, is := box.(*TableRowBox)
	return is
}

type typeTableRowBox struct{}

func (t typeTableColumnGroupBox) AnonymousFrom(parent Box, children []Box) Box {
	return TableColumnGroupBoxAnonymousFrom(parent, children)
}

func (t typeTableColumnGroupBox) IsInstance(box Box) bool {
	_, is := box.(*TableColumnGroupBox)
	return is
}

type typeTableColumnGroupBox struct{}

func (t typeTableColumnBox) AnonymousFrom(parent Box, children []Box) Box {
	return TableColumnBoxAnonymousFrom(parent, children)
}

func (t typeTableColumnBox) IsInstance(box Box) bool {
	_, is := box.(*TableColumnBox)
	return is
}

type typeTableColumnBox struct{}

func (t typeTableCellBox) AnonymousFrom(parent Box, children []Box) Box {
	return TableCellBoxAnonymousFrom(parent, children)
}

func (t typeTableCellBox) IsInstance(box Box) bool {
	_, is := box.(*TableCellBox)
	return is
}

type typeTableCellBox struct{}
