// Generated by makebreaks.go
// DO NOT EDIT

package unicodedata

// data from : https://unicode.org/Public/UCD/latest/ucd/auxiliary/SentenceBreakProperty.txt
// and :https://unicode.org/Public/UCD/latest/ucd/IndicSyllabicCategory.txt

func IsVirama(wc rune) bool {
	if wc >= 0x094d && wc <= 0x0bcd {
		if wc == 0x094d {
			return true
		}
		if wc == 0x09cd ||
			wc == 0x0a4d {
			return true
		}
		if wc == 0x0acd {
			return true
		}
		if wc == 0x0b4d ||
			wc == 0x0bcd {
			return true
		}
		return false
	}
	if wc >= 0x0c4d && wc <= 0xa8c4 {
		if wc == 0x0c4d {
			return true
		}
		if wc == 0x0ccd ||
			wc == 0x0d4d {
			return true
		}
		if wc == 0x0dca {
			return true
		}
		if wc == 0x1b44 ||
			wc == 0xa806 ||
			wc == 0xa8c4 {
			return true
		}
		return false
	}
	if wc >= 0xa9c0 && wc <= 0x1134d {
		if wc == 0xa9c0 {
			return true
		}
		if wc == 0x11046 ||
			wc == 0x110b9 {
			return true
		}
		if wc == 0x111c0 {
			return true
		}
		if wc == 0x11235 ||
			wc == 0x1134d {
			return true
		}
		return false
	}
	if wc >= 0x11442 && wc <= 0x11c3f {
		if wc == 0x11442 ||
			wc == 0x114c2 {
			return true
		}
		if wc == 0x115bf ||
			wc == 0x1163f {
			return true
		}
		if wc == 0x116b6 ||
			wc == 0x11839 {
			return true
		}
		if wc == 0x119e0 ||
			wc == 0x11c3f {
			return true
		}
		return false
	}
	return false
}

func IsVowel_Dependent(wc rune) bool {
	if wc >= 0x093a && wc <= 0x0cc4 {
		if wc >= 0x093a && wc <= 0x09cc {
			if (wc >= 0x093a && wc <= 0x093b) ||
				(wc >= 0x093e && wc <= 0x094c) {
				return true
			}
			if (wc >= 0x094e && wc <= 0x094f) ||
				(wc >= 0x0955 && wc <= 0x0957) {
				return true
			}
			if (wc >= 0x0962 && wc <= 0x0963) ||
				(wc >= 0x09be && wc <= 0x09c4) {
				return true
			}
			if (wc >= 0x09c7 && wc <= 0x09c8) ||
				(wc >= 0x09cb && wc <= 0x09cc) {
				return true
			}
			return false
		}
		if wc >= 0x09d7 && wc <= 0x0acc {
			if wc == 0x09d7 ||
				(wc >= 0x09e2 && wc <= 0x09e3) {
				return true
			}
			if (wc >= 0x0a3e && wc <= 0x0a42) ||
				(wc >= 0x0a47 && wc <= 0x0a48) {
				return true
			}
			if (wc >= 0x0a4b && wc <= 0x0a4c) ||
				(wc >= 0x0abe && wc <= 0x0ac5) {
				return true
			}
			if (wc >= 0x0ac7 && wc <= 0x0ac9) ||
				(wc >= 0x0acb && wc <= 0x0acc) {
				return true
			}
			return false
		}
		if wc >= 0x0ae2 && wc <= 0x0bc8 {
			if (wc >= 0x0ae2 && wc <= 0x0ae3) ||
				(wc >= 0x0b3e && wc <= 0x0b44) {
				return true
			}
			if (wc >= 0x0b47 && wc <= 0x0b48) ||
				(wc >= 0x0b4b && wc <= 0x0b4c) {
				return true
			}
			if (wc >= 0x0b56 && wc <= 0x0b57) ||
				(wc >= 0x0b62 && wc <= 0x0b63) {
				return true
			}
			if (wc >= 0x0bbe && wc <= 0x0bc2) ||
				(wc >= 0x0bc6 && wc <= 0x0bc8) {
				return true
			}
			return false
		}
		if wc >= 0x0bca && wc <= 0x0cc4 {
			if (wc >= 0x0bca && wc <= 0x0bcc) ||
				wc == 0x0bd7 {
				return true
			}
			if (wc >= 0x0c3e && wc <= 0x0c44) ||
				(wc >= 0x0c46 && wc <= 0x0c48) {
				return true
			}
			if (wc >= 0x0c4a && wc <= 0x0c4c) ||
				(wc >= 0x0c55 && wc <= 0x0c56) {
				return true
			}
			if (wc >= 0x0c62 && wc <= 0x0c63) ||
				(wc >= 0x0cbe && wc <= 0x0cc4) {
				return true
			}
			return false
		}
		return false
	}
	if wc >= 0x0cc6 && wc <= 0x1773 {
		if wc >= 0x0cc6 && wc <= 0x0d57 {
			if (wc >= 0x0cc6 && wc <= 0x0cc8) ||
				(wc >= 0x0cca && wc <= 0x0ccc) {
				return true
			}
			if (wc >= 0x0cd5 && wc <= 0x0cd6) ||
				(wc >= 0x0ce2 && wc <= 0x0ce3) {
				return true
			}
			if (wc >= 0x0d3e && wc <= 0x0d44) ||
				(wc >= 0x0d46 && wc <= 0x0d48) {
				return true
			}
			if (wc >= 0x0d4a && wc <= 0x0d4c) ||
				wc == 0x0d57 {
				return true
			}
			return false
		}
		if wc >= 0x0d62 && wc <= 0x0e47 {
			if (wc >= 0x0d62 && wc <= 0x0d63) ||
				(wc >= 0x0dcf && wc <= 0x0dd4) {
				return true
			}
			if wc == 0x0dd6 ||
				(wc >= 0x0dd8 && wc <= 0x0ddf) {
				return true
			}
			if (wc >= 0x0df2 && wc <= 0x0df3) ||
				(wc >= 0x0e30 && wc <= 0x0e39) {
				return true
			}
			if (wc >= 0x0e40 && wc <= 0x0e45) ||
				wc == 0x0e47 {
				return true
			}
			return false
		}
		if wc >= 0x0eb0 && wc <= 0x1062 {
			if (wc >= 0x0eb0 && wc <= 0x0eb9) ||
				wc == 0x0ebb {
				return true
			}
			if (wc >= 0x0ec0 && wc <= 0x0ec4) ||
				(wc >= 0x0f71 && wc <= 0x0f7d) {
				return true
			}
			if (wc >= 0x0f80 && wc <= 0x0f81) ||
				(wc >= 0x102b && wc <= 0x1035) {
				return true
			}
			if (wc >= 0x1056 && wc <= 0x1059) ||
				wc == 0x1062 {
				return true
			}
			return false
		}
		if wc >= 0x1067 && wc <= 0x1773 {
			if (wc >= 0x1067 && wc <= 0x1068) ||
				(wc >= 0x1071 && wc <= 0x1074) {
				return true
			}
			if (wc >= 0x1083 && wc <= 0x1086) ||
				(wc >= 0x109c && wc <= 0x109d) {
				return true
			}
			if (wc >= 0x1712 && wc <= 0x1713) ||
				(wc >= 0x1732 && wc <= 0x1733) {
				return true
			}
			if (wc >= 0x1752 && wc <= 0x1753) ||
				(wc >= 0x1772 && wc <= 0x1773) {
				return true
			}
			return false
		}
		return false
	}
	if wc >= 0x17b6 && wc <= 0x11233 {
		if wc >= 0x17b6 && wc <= 0x1b43 {
			if (wc >= 0x17b6 && wc <= 0x17c5) ||
				wc == 0x17c8 {
				return true
			}
			if (wc >= 0x1920 && wc <= 0x1928) ||
				wc == 0x193a {
				return true
			}
			if (wc >= 0x19b0 && wc <= 0x19c0) ||
				(wc >= 0x1a17 && wc <= 0x1a1b) {
				return true
			}
			if (wc >= 0x1a61 && wc <= 0x1a73) ||
				(wc >= 0x1b35 && wc <= 0x1b43) {
				return true
			}
			return false
		}
		if wc >= 0x1ba4 && wc <= 0xa94e {
			if (wc >= 0x1ba4 && wc <= 0x1ba9) ||
				(wc >= 0x1be7 && wc <= 0x1bef) {
				return true
			}
			if (wc >= 0x1c26 && wc <= 0x1c2c) ||
				wc == 0xa802 {
				return true
			}
			if (wc >= 0xa823 && wc <= 0xa827) ||
				(wc >= 0xa8b5 && wc <= 0xa8c3) {
				return true
			}
			if wc == 0xa8ff ||
				(wc >= 0xa947 && wc <= 0xa94e) {
				return true
			}
			return false
		}
		if wc >= 0xa9b4 && wc <= 0x10a06 {
			if (wc >= 0xa9b4 && wc <= 0xa9bc) ||
				wc == 0xa9e5 {
				return true
			}
			if (wc >= 0xaa29 && wc <= 0xaa32) ||
				(wc >= 0xaab0 && wc <= 0xaabe) {
				return true
			}
			if (wc >= 0xaaeb && wc <= 0xaaef) ||
				(wc >= 0xabe3 && wc <= 0xabea) {
				return true
			}
			if (wc >= 0x10a01 && wc <= 0x10a03) ||
				(wc >= 0x10a05 && wc <= 0x10a06) {
				return true
			}
			return false
		}
		if wc >= 0x10a0c && wc <= 0x11233 {
			if (wc >= 0x10a0c && wc <= 0x10a0d) ||
				(wc >= 0x11038 && wc <= 0x11045) {
				return true
			}
			if (wc >= 0x110b0 && wc <= 0x110b8) ||
				(wc >= 0x11127 && wc <= 0x11132) {
				return true
			}
			if (wc >= 0x11145 && wc <= 0x11146) ||
				(wc >= 0x111b3 && wc <= 0x111bf) {
				return true
			}
			if (wc >= 0x111cb && wc <= 0x111cc) ||
				(wc >= 0x1122c && wc <= 0x11233) {
				return true
			}
			return false
		}
		return false
	}
	if wc >= 0x112e0 && wc <= 0x11ef6 {
		if wc >= 0x112e0 && wc <= 0x114be {
			if (wc >= 0x112e0 && wc <= 0x112e8) ||
				(wc >= 0x1133e && wc <= 0x11344) {
				return true
			}
			if (wc >= 0x11347 && wc <= 0x11348) ||
				(wc >= 0x1134b && wc <= 0x1134c) {
				return true
			}
			if wc == 0x11357 ||
				(wc >= 0x11362 && wc <= 0x11363) {
				return true
			}
			if (wc >= 0x11435 && wc <= 0x11441) ||
				(wc >= 0x114b0 && wc <= 0x114be) {
				return true
			}
			return false
		}
		if wc >= 0x115af && wc <= 0x11836 {
			if (wc >= 0x115af && wc <= 0x115b5) ||
				(wc >= 0x115b8 && wc <= 0x115bb) {
				return true
			}
			if (wc >= 0x115dc && wc <= 0x115dd) ||
				(wc >= 0x11630 && wc <= 0x1163c) {
				return true
			}
			if wc == 0x11640 ||
				(wc >= 0x116ad && wc <= 0x116b5) {
				return true
			}
			if (wc >= 0x11720 && wc <= 0x1172a) ||
				(wc >= 0x1182c && wc <= 0x11836) {
				return true
			}
			return false
		}
		if wc >= 0x119d1 && wc <= 0x11cb4 {
			if (wc >= 0x119d1 && wc <= 0x119d7) ||
				(wc >= 0x119da && wc <= 0x119dd) {
				return true
			}
			if wc == 0x119e4 ||
				(wc >= 0x11a01 && wc <= 0x11a0a) {
				return true
			}
			if (wc >= 0x11a51 && wc <= 0x11a5b) ||
				(wc >= 0x11c2f && wc <= 0x11c36) {
				return true
			}
			if (wc >= 0x11c38 && wc <= 0x11c3b) ||
				(wc >= 0x11cb0 && wc <= 0x11cb4) {
				return true
			}
			return false
		}
		if wc >= 0x11d31 && wc <= 0x11ef6 {
			if (wc >= 0x11d31 && wc <= 0x11d36) ||
				wc == 0x11d3a {
				return true
			}
			if (wc >= 0x11d3c && wc <= 0x11d3d) ||
				wc == 0x11d3f {
				return true
			}
			if wc == 0x11d43 ||
				(wc >= 0x11d8a && wc <= 0x11d8e) {
				return true
			}
			if (wc >= 0x11d90 && wc <= 0x11d91) ||
				(wc >= 0x11d93 && wc <= 0x11d94) ||
				(wc >= 0x11ef3 && wc <= 0x11ef6) {
				return true
			}
			return false
		}
		return false
	}
	return false
}

func IsSTerm(wc rune) bool {
	if wc >= 0x0021 && wc <= 0x1803 {
		if wc == 0x0021 ||
			wc == 0x003f ||
			wc == 0x0589 ||
			(wc >= 0x061e && wc <= 0x061f) {
			return true
		}
		if wc == 0x06d4 ||
			(wc >= 0x0700 && wc <= 0x0702) ||
			wc == 0x07f9 ||
			wc == 0x0837 {
			return true
		}
		if wc == 0x0839 ||
			(wc >= 0x083d && wc <= 0x083e) ||
			(wc >= 0x0964 && wc <= 0x0965) ||
			(wc >= 0x104a && wc <= 0x104b) {
			return true
		}
		if wc >= 0x1362 && wc <= 0x1803 {
			if wc == 0x1362 {
				return true
			}
			if wc >= 0x1367 && wc <= 0x1368 {
				return true
			}
			if wc == 0x166e {
				return true
			}
			if (wc >= 0x1735 && wc <= 0x1736) ||
				wc == 0x1803 {
				return true
			}
			return false
		}
		return false
	}
	if wc >= 0x1809 && wc <= 0xa8cf {
		if wc == 0x1809 ||
			(wc >= 0x1944 && wc <= 0x1945) ||
			(wc >= 0x1aa8 && wc <= 0x1aab) ||
			(wc >= 0x1b5a && wc <= 0x1b5b) {
			return true
		}
		if wc >= 0x1b5e && wc <= 0x2049 {
			if wc >= 0x1b5e && wc <= 0x1b5f {
				return true
			}
			if wc >= 0x1c3b && wc <= 0x1c3c {
				return true
			}
			if wc >= 0x1c7e && wc <= 0x1c7f {
				return true
			}
			if (wc >= 0x203c && wc <= 0x203d) ||
				(wc >= 0x2047 && wc <= 0x2049) {
				return true
			}
			return false
		}
		if wc == 0x2e2e ||
			wc == 0x2e3c ||
			wc == 0x3002 ||
			wc == 0xa4ff {
			return true
		}
		if wc >= 0xa60e && wc <= 0xa8cf {
			if wc >= 0xa60e && wc <= 0xa60f {
				return true
			}
			if wc == 0xa6f3 {
				return true
			}
			if wc == 0xa6f7 {
				return true
			}
			if (wc >= 0xa876 && wc <= 0xa877) ||
				(wc >= 0xa8ce && wc <= 0xa8cf) {
				return true
			}
			return false
		}
		return false
	}
	if wc >= 0xa92f && wc <= 0x111df {
		if wc == 0xa92f ||
			(wc >= 0xa9c8 && wc <= 0xa9c9) ||
			(wc >= 0xaa5d && wc <= 0xaa5f) ||
			(wc >= 0xaaf0 && wc <= 0xaaf1) {
			return true
		}
		if wc == 0xabeb ||
			(wc >= 0xfe56 && wc <= 0xfe57) ||
			wc == 0xff01 ||
			wc == 0xff1f {
			return true
		}
		if wc == 0xff61 ||
			(wc >= 0x10a56 && wc <= 0x10a57) ||
			(wc >= 0x10f55 && wc <= 0x10f59) ||
			(wc >= 0x11047 && wc <= 0x11048) {
			return true
		}
		if wc >= 0x110be && wc <= 0x111df {
			if wc >= 0x110be && wc <= 0x110c1 {
				return true
			}
			if wc >= 0x11141 && wc <= 0x11143 {
				return true
			}
			if wc >= 0x111c5 && wc <= 0x111c6 {
				return true
			}
			if wc == 0x111cd ||
				(wc >= 0x111de && wc <= 0x111df) {
				return true
			}
			return false
		}
		return false
	}
	if wc >= 0x11238 && wc <= 0x1da88 {
		if (wc >= 0x11238 && wc <= 0x11239) ||
			(wc >= 0x1123b && wc <= 0x1123c) ||
			wc == 0x112a9 ||
			(wc >= 0x1144b && wc <= 0x1144c) {
			return true
		}
		if wc >= 0x115c2 && wc <= 0x11a43 {
			if wc >= 0x115c2 && wc <= 0x115c3 {
				return true
			}
			if wc >= 0x115c9 && wc <= 0x115d7 {
				return true
			}
			if wc >= 0x11641 && wc <= 0x11642 {
				return true
			}
			if (wc >= 0x1173c && wc <= 0x1173e) ||
				(wc >= 0x11a42 && wc <= 0x11a43) {
				return true
			}
			return false
		}
		if (wc >= 0x11a9b && wc <= 0x11a9c) ||
			(wc >= 0x11c41 && wc <= 0x11c42) ||
			(wc >= 0x11ef7 && wc <= 0x11ef8) ||
			(wc >= 0x16a6e && wc <= 0x16a6f) {
			return true
		}
		if wc >= 0x16af5 && wc <= 0x1da88 {
			if wc == 0x16af5 {
				return true
			}
			if (wc >= 0x16b37 && wc <= 0x16b38) ||
				wc == 0x16b44 {
				return true
			}
			if wc == 0x16e98 {
				return true
			}
			if wc == 0x1bc9f ||
				wc == 0x1da88 {
				return true
			}
			return false
		}
		return false
	}
	return false
}
