package boxes

// Code generated by macros/boxes.py DO NOT EDIT

// An atomic box in an inline formatting context.
// This inline-level box cannot be split for line breaks.
type AtomicInlineLevelBoxITF interface {
	InlineLevelBoxITF
	isAtomicInlineLevelBox()
}

func (AtomicInlineLevelBox) Type() BoxType { return TypeAtomicInlineLevelBox }

// A block-level box that is also a block container.
// A non-replaced element with a ``display`` value of ``block``, ``list-item``
// generates a block box.
type BlockBoxITF interface {
	BlockLevelBoxITF
	BlockContainerBoxITF
	isBlockBox()
}

func (BlockBox) Type() BoxType { return TypeBlockBox }

// A box that contains only block-level boxes or only line boxes.
// A box that either contains only block-level boxes or establishes an inline
// formatting context and thus contains only line boxes.
// A non-replaced element with a ``display`` value of ``block``,
// ``list-item``, ``inline-block`` or 'table-cell' generates a block container
// box.
type BlockContainerBoxITF interface {
	ParentBoxITF
	isBlockContainerBox()
}

func (BlockContainerBox) Type() BoxType { return TypeBlockContainerBox }

// A box that participates in an block formatting context.
// An element with a ``display`` value of ``block``, ``list-item`` or
// ``table`` generates a block-level box.
type BlockLevelBoxITF interface {
	BoxITF
	isBlockLevelBox()
	methodsBlockLevelBox
}

func (BlockLevelBox) Type() BoxType { return TypeBlockLevelBox }

// A box that is both replaced and block-level.
// A replaced element with a ``display`` value of ``block``, ``liste-item`` or
// ``table`` generates a block-level replaced box.
type BlockReplacedBoxITF interface {
	BlockLevelBoxITF
	ReplacedBoxITF
	isBlockReplacedBox()
}

func (BlockReplacedBox) Type() BoxType { return TypeBlockReplacedBox }

// Abstract base class for all boxes.
type BoxITF interface {
	isBox()
	methodsBox
}

func (Box) Type() BoxType { return TypeBox }

// A box that is both block-level and a flex container.
// It behaves as block on the outside and as a flex container on the inside.
type FlexBoxITF interface {
	BlockLevelBoxITF
	FlexContainerBoxITF
	isFlexBox()
}

func (FlexBox) Type() BoxType { return TypeFlexBox }

// A box that contains only flex-items.
type FlexContainerBoxITF interface {
	ParentBoxITF
	isFlexContainerBox()
}

func (FlexContainerBox) Type() BoxType { return TypeFlexContainerBox }

// A box that is both inline-level and a block container.
// It behaves as inline on the outside and as a block on the inside.
// A non-replaced element with a 'display' value of 'inline-block' generates
// an inline-block box.
type InlineBlockBoxITF interface {
	AtomicInlineLevelBoxITF
	BlockContainerBoxITF
	isInlineBlockBox()
}

func (InlineBlockBox) Type() BoxType { return TypeInlineBlockBox }

// An inline box with inline children.
// A box that participates in an inline formatting context and whose content
// also participates in that inline formatting context.
// A non-replaced element with a ``display`` value of ``inline`` generates an
// inline box.
type InlineBoxITF interface {
	InlineLevelBoxITF
	ParentBoxITF
	isInlineBox()
}

func (InlineBox) Type() BoxType { return TypeInlineBox }

// A box that is both inline-level and a flex container.
// It behaves as inline on the outside and as a flex container on the inside.
type InlineFlexBoxITF interface {
	InlineLevelBoxITF
	FlexContainerBoxITF
	isInlineFlexBox()
}

func (InlineFlexBox) Type() BoxType { return TypeInlineFlexBox }

// A box that participates in an inline formatting context.
// An inline-level box that is not an inline box is said to be "atomic". Such
// boxes are inline blocks, replaced elements and inline tables.
// An element with a ``display`` value of ``inline``, ``inline-table``, or
// ``inline-block`` generates an inline-level box.
type InlineLevelBoxITF interface {
	BoxITF
	isInlineLevelBox()
}

func (InlineLevelBox) Type() BoxType { return TypeInlineLevelBox }

// A box that is both replaced and inline-level.
// A replaced element with a ``display`` value of ``inline``,
// ``inline-table``, or ``inline-block`` generates an inline-level replaced
// box.
type InlineReplacedBoxITF interface {
	AtomicInlineLevelBoxITF
	ReplacedBoxITF
	isInlineReplacedBox()
}

func (InlineReplacedBox) Type() BoxType { return TypeInlineReplacedBox }

// Box for elements with ``display: inline-table``
type InlineTableBoxITF interface {
	TableBoxITF
	isInlineTableBox()
}

func (InlineTableBox) Type() BoxType { return TypeInlineTableBox }

// A box that represents a line in an inline formatting context.
// Can only contain inline-level boxes.
// In early stages of building the box tree a single line box contains many
// consecutive inline boxes. Later, during layout phase, each line boxes will
// be split into multiple line boxes, one for each actual line.
type LineBoxITF interface {
	ParentBoxITF
	isLineBox()
}

func (LineBox) Type() BoxType { return TypeLineBox }

// Box in page margins, as defined in CSS3 Paged Media
type MarginBoxITF interface {
	BlockContainerBoxITF
	isMarginBox()
}

func (MarginBox) Type() BoxType { return TypeMarginBox }

// Box for a page.
// Initially the whole document will be in the box for the root element.
// During layout a new page box is created after every page break.
type PageBoxITF interface {
	ParentBoxITF
	isPageBox()
}

func (PageBox) Type() BoxType { return TypePageBox }

// A box that has children.
type ParentBoxITF interface {
	BoxITF
	isParentBox()
}

func (ParentBox) Type() BoxType { return TypeParentBox }

// A box whose content is replaced.
// For example, ``<img>`` are replaced: their content is rendered externally
// and is opaque from CSS’s point of view.
type ReplacedBoxITF interface {
	BoxITF
	isReplacedBox()
	methodsReplacedBox
}

func (ReplacedBox) Type() BoxType { return TypeReplacedBox }

// Box for elements with ``display: table``
type TableBoxITF interface {
	BlockLevelBoxITF
	ParentBoxITF
	isTableBox()
	methodsTableBox
}

func (TableBox) Type() BoxType { return TypeTableBox }

// Box for elements with ``display: table-caption``
type TableCaptionBoxITF interface {
	BlockBoxITF
	isTableCaptionBox()
}

func (TableCaptionBox) Type() BoxType { return TypeTableCaptionBox }

// Box for elements with ``display: table-cell``
type TableCellBoxITF interface {
	BlockContainerBoxITF
	isTableCellBox()
}

func (TableCellBox) Type() BoxType { return TypeTableCellBox }

// Box for elements with ``display: table-column``
type TableColumnBoxITF interface {
	ParentBoxITF
	isTableColumnBox()
}

func (TableColumnBox) Type() BoxType { return TypeTableColumnBox }

// Box for elements with ``display: table-column-group``
type TableColumnGroupBoxITF interface {
	ParentBoxITF
	isTableColumnGroupBox()
}

func (TableColumnGroupBox) Type() BoxType { return TypeTableColumnGroupBox }

// Box for elements with ``display: table-row``
type TableRowBoxITF interface {
	ParentBoxITF
	isTableRowBox()
}

func (TableRowBox) Type() BoxType { return TypeTableRowBox }

// Box for elements with ``display: table-row-group``
type TableRowGroupBoxITF interface {
	ParentBoxITF
	isTableRowGroupBox()
}

func (TableRowGroupBox) Type() BoxType { return TypeTableRowGroupBox }

// A box that contains only text and has no box children.
// Any text in the document ends up in a text box. What CSS calls "anonymous
// inline boxes" are also text boxes.
type TextBoxITF interface {
	InlineLevelBoxITF
	isTextBox()
}

func (TextBox) Type() BoxType { return TypeTextBox }

// BoxType represents a box type.
type BoxType uint8

const (
	invalidType BoxType = iota
	TypeAtomicInlineLevelBox
	TypeBlockBox
	TypeBlockContainerBox
	TypeBlockLevelBox
	TypeBlockReplacedBox
	TypeBox
	TypeFlexBox
	TypeFlexContainerBox
	TypeInlineBlockBox
	TypeInlineBox
	TypeInlineFlexBox
	TypeInlineLevelBox
	TypeInlineReplacedBox
	TypeInlineTableBox
	TypeLineBox
	TypeMarginBox
	TypePageBox
	TypeParentBox
	TypeReplacedBox
	TypeTableBox
	TypeTableCaptionBox
	TypeTableCellBox
	TypeTableColumnBox
	TypeTableColumnGroupBox
	TypeTableRowBox
	TypeTableRowGroupBox
	TypeTextBox
)

// Returns true is the box is an instance of t.
func (t BoxType) IsInstance(box BoxITF) bool {
	var isInstance bool
	switch t {
	case TypeAtomicInlineLevelBox:
		_, isInstance = box.(AtomicInlineLevelBoxITF)
	case TypeBlockBox:
		_, isInstance = box.(BlockBoxITF)
	case TypeBlockContainerBox:
		_, isInstance = box.(BlockContainerBoxITF)
	case TypeBlockLevelBox:
		_, isInstance = box.(BlockLevelBoxITF)
	case TypeBlockReplacedBox:
		_, isInstance = box.(BlockReplacedBoxITF)
	case TypeBox:
		_, isInstance = box.(BoxITF)
	case TypeFlexBox:
		_, isInstance = box.(FlexBoxITF)
	case TypeFlexContainerBox:
		_, isInstance = box.(FlexContainerBoxITF)
	case TypeInlineBlockBox:
		_, isInstance = box.(InlineBlockBoxITF)
	case TypeInlineBox:
		_, isInstance = box.(InlineBoxITF)
	case TypeInlineFlexBox:
		_, isInstance = box.(InlineFlexBoxITF)
	case TypeInlineLevelBox:
		_, isInstance = box.(InlineLevelBoxITF)
	case TypeInlineReplacedBox:
		_, isInstance = box.(InlineReplacedBoxITF)
	case TypeInlineTableBox:
		_, isInstance = box.(InlineTableBoxITF)
	case TypeLineBox:
		_, isInstance = box.(LineBoxITF)
	case TypeMarginBox:
		_, isInstance = box.(MarginBoxITF)
	case TypePageBox:
		_, isInstance = box.(PageBoxITF)
	case TypeParentBox:
		_, isInstance = box.(ParentBoxITF)
	case TypeReplacedBox:
		_, isInstance = box.(ReplacedBoxITF)
	case TypeTableBox:
		_, isInstance = box.(TableBoxITF)
	case TypeTableCaptionBox:
		_, isInstance = box.(TableCaptionBoxITF)
	case TypeTableCellBox:
		_, isInstance = box.(TableCellBoxITF)
	case TypeTableColumnBox:
		_, isInstance = box.(TableColumnBoxITF)
	case TypeTableColumnGroupBox:
		_, isInstance = box.(TableColumnGroupBoxITF)
	case TypeTableRowBox:
		_, isInstance = box.(TableRowBoxITF)
	case TypeTableRowGroupBox:
		_, isInstance = box.(TableRowGroupBoxITF)
	case TypeTextBox:
		_, isInstance = box.(TextBoxITF)
	}
	return isInstance
}

func (t BoxType) String() string {
	switch t {
	case TypeAtomicInlineLevelBox:
		return "AtomicInlineLevelBox"
	case TypeBlockBox:
		return "BlockBox"
	case TypeBlockContainerBox:
		return "BlockContainerBox"
	case TypeBlockLevelBox:
		return "BlockLevelBox"
	case TypeBlockReplacedBox:
		return "BlockReplacedBox"
	case TypeBox:
		return "Box"
	case TypeFlexBox:
		return "FlexBox"
	case TypeFlexContainerBox:
		return "FlexContainerBox"
	case TypeInlineBlockBox:
		return "InlineBlockBox"
	case TypeInlineBox:
		return "InlineBox"
	case TypeInlineFlexBox:
		return "InlineFlexBox"
	case TypeInlineLevelBox:
		return "InlineLevelBox"
	case TypeInlineReplacedBox:
		return "InlineReplacedBox"
	case TypeInlineTableBox:
		return "InlineTableBox"
	case TypeLineBox:
		return "LineBox"
	case TypeMarginBox:
		return "MarginBox"
	case TypePageBox:
		return "PageBox"
	case TypeParentBox:
		return "ParentBox"
	case TypeReplacedBox:
		return "ReplacedBox"
	case TypeTableBox:
		return "TableBox"
	case TypeTableCaptionBox:
		return "TableCaptionBox"
	case TypeTableCellBox:
		return "TableCellBox"
	case TypeTableColumnBox:
		return "TableColumnBox"
	case TypeTableColumnGroupBox:
		return "TableColumnGroupBox"
	case TypeTableRowBox:
		return "TableRowBox"
	case TypeTableRowGroupBox:
		return "TableRowGroupBox"
	case TypeTextBox:
		return "TextBox"
	}
	return "<invalid box type>"
}

var (
	_ AtomicInlineLevelBoxITF = (*AtomicInlineLevelBox)(nil)
	_ BlockBoxITF             = (*BlockBox)(nil)
	_ BlockContainerBoxITF    = (*BlockContainerBox)(nil)
	_ BlockLevelBoxITF        = (*BlockLevelBox)(nil)
	_ BlockReplacedBoxITF     = (*BlockReplacedBox)(nil)
	_ BoxITF                  = (*Box)(nil)
	_ FlexBoxITF              = (*FlexBox)(nil)
	_ FlexContainerBoxITF     = (*FlexContainerBox)(nil)
	_ InlineBlockBoxITF       = (*InlineBlockBox)(nil)
	_ InlineBoxITF            = (*InlineBox)(nil)
	_ InlineFlexBoxITF        = (*InlineFlexBox)(nil)
	_ InlineLevelBoxITF       = (*InlineLevelBox)(nil)
	_ InlineReplacedBoxITF    = (*InlineReplacedBox)(nil)
	_ InlineTableBoxITF       = (*InlineTableBox)(nil)
	_ LineBoxITF              = (*LineBox)(nil)
	_ MarginBoxITF            = (*MarginBox)(nil)
	_ PageBoxITF              = (*PageBox)(nil)
	_ ParentBoxITF            = (*ParentBox)(nil)
	_ ReplacedBoxITF          = (*ReplacedBox)(nil)
	_ TableBoxITF             = (*TableBox)(nil)
	_ TableCaptionBoxITF      = (*TableCaptionBox)(nil)
	_ TableCellBoxITF         = (*TableCellBox)(nil)
	_ TableColumnBoxITF       = (*TableColumnBox)(nil)
	_ TableColumnGroupBoxITF  = (*TableColumnGroupBox)(nil)
	_ TableRowBoxITF          = (*TableRowBox)(nil)
	_ TableRowGroupBoxITF     = (*TableRowGroupBox)(nil)
	_ TextBoxITF              = (*TextBox)(nil)
)
