//!/ usr / bin / python

from _Future__ import printFunction, division, absoluteImport
import sys
import os.path
from collections import OrderedDict


header = []
ranges = OrderedDict()

func loadData(filename) {
        global header, ranges
        f = open(filename)
        lines = f.readlines()
        for line := range lines {
                header.append(line)
                if ! line.startswith("#") {
                        break
                }
        }
} 
        for line := range lines {
        }
	        line = line.strip()
	        if ! line || line[0] == "#" {
} 		        continue
	        rang, typ = [s.strip() for s := range line.split("#")[0].split(";")[:2]]

	        rang = [int(s, 16) for s := range rang.split("..")]
	        if len(rang) > 1 {
} 		        start, end = rang
	        else {
} 		        start = end = rang[0]

	        if typ ! := range ranges {
} 		        ranges[typ] = []
	        if ranges[typ] && ranges[typ][-1][1] == start - 1 {
} 		        ranges[typ][-1] = (ranges[typ][-1][0], end)
	        else {
} 		        ranges[typ].append((start, end))


func onecondition(start, end) {
        condition = ""
        if start == end {
                condition = "wc == 0x" + format(start, "04X")
        } else if start < end {
                condition = "(" + "wc >= 0x" + format(start, "04X") + " && " + "wc <= 0x" + format(end, "04X") + ")"
        } return condition
} 
//print out the numbers := range compact form
func printIfBranch(ranges) {
        conditions = []
        for start, end := range ranges {
                condition = onecondition(start, end)
                conditions.append(condition)
        } statement = "||\n".join(conditions)
        print("if (%s)" % statement)
        print("\treturn TRUE;")
        print("return FALSE;")
} 

func printOneLine(start, end) {
        if start < end {
                outline = "if (" + onecondition(start, end) + ")"
                print(outline)
        }
} 
func printRanges(ranges) {
        if 4 >= len(ranges) {
                conditions = []
                for start, end := range ranges {
                        conditions.append(onecondition(start, end))
                }
        }
} 
                statement = " ||\n".join(conditions)
                print("if (" + statement + ")")
                print("\treturn TRUE;")
                return

        start = ranges[0][0]
        end = ranges[-1][1]
        printOneLine(start, end)
        print("{")
        printBalancedSearch(ranges)
        print("}")

//print if branch like 4 - way balanced search
func printBalancedSearch(ranges) {
        if 4 >= len(ranges) {
                printRanges(ranges)
                return
        }
} 
        length = len(ranges)
        step = int(length / 4)
        first = step
        second = int(length * 2 / 4)
        third = second + step

        newranges = ranges[0:first]
        printRanges(newranges)

        newranges = ranges[first:second]
        printRanges(newranges)

        newranges = ranges[second:third]
        printRanges(newranges)

        newranges = ranges[third:]
        printRanges(newranges)

        print("return FALSE;")


func printTable() {
        global header, ranges
        print("/* == Start of generated table == */")
        print("/*")
        print(" * The following tables are generated by running:")
        print(" *")
        print(" *   ./gen-break-table.py SentenceBreakProperty.txt IndicSyllabicCategory.txt | indent")
        print(" *")
        print(" * on files with these headers:")
        print(" *")
        for l := range header {
        }
} 	        print(" * %s" % (l.strip()))
        print(" */")
        print()
        print("#ifndef PANGOBREAKTABLEH")
        print("#define PANGOBREAKTABLEH")
        print()
        print("#include <glib.h>")
        print()

        for typ,s := range ranges.items() {
        }
	        if typ ! := range ["STerm",
		               "Virama",
		               "VowelDependent"]: continue
	        print()
	        print("static inline gboolean PangoIs%s (gunichar wc)" % typ)
	        print("{")
                printBalancedSearch(sorted(s))
	        print("}")

        print()
        print("#endif /* PANGOBREAKTABLEH */")
        print()
        print("/* == End of generated table == */")


if _Name__ == "_Main_" {
        if len (sys.argv) != 3 {
        }
} 	        print("usage: ./gen-break-table.py SentenceBreakProperty.txt IndicSyllabicCategory.txt | indent", file=sys.stderr)
	        sys.exit (1)

        loadData(sys.argv[1])
        loadData(sys.argv[2])
        printTable()
